import test from 'node:test';
import assert from 'node:assert/strict';
import {distance, cumulative, atDistance, elevationStats, outAndBack, closeLoop, isClosedLoop, loopPath, rotatedLoop, nearestOnPath} from '../dist/src/geometry.js';
import {defaults, simulate, durationFor, parseClock, clock, validateActivity, loopPlan, plannedPath, computeSplits, splitBoundaries} from '../dist/src/model.js';
import {exportGPX, safeFilename} from '../dist/src/gpx.js';
const path=[{lon:0,lat:0,ele:10},{lon:0.045,lat:0,ele:20}];
test('geodesic distance and interpolation',()=>{assert.ok(Math.abs(distance(path[0],path[1])-5003.78)<1);let c=cumulative(path);assert.ok(Math.abs(atDistance(path,c,c.at(-1)/2).lon-.0225)<1e-6);});
test('known pace and speed arithmetic',()=>{assert.equal(durationFor(10000,'run',300,20),3000);assert.equal(durationFor(5000,'run',240,20),1200);assert.equal(durationFor(20000,'ride',300,20),3600);});
test('clock rounds safely',()=>{assert.equal(clock(299.8),'5:00');assert.equal(parseClock('1:02:03'),3723);assert.throws(()=>parseClock('5:99'));});
test('turnaround has no duplicated pivot',()=>{let a=outAndBack([1,2,3]);assert.deepEqual(a,[1,2,3,2,1]);});
test('closing a loop returns to the start and tolerates an empty route',()=>{assert.deepEqual(closeLoop([1,2,3]),[1,2,3,1]);assert.deepEqual(closeLoop([]),[]);});
const square=[{lat:0,lon:0},{lat:0,lon:.01},{lat:.01,lon:.01},{lat:.01,lon:0},{lat:0,lon:0}];
test('closed loops rotate from a start fraction and walk whole or partial laps',()=>{
 const total=cumulative(square).at(-1);
 assert.equal(isClosedLoop(square),true);assert.equal(isClosedLoop(path),false);assert.equal(isClosedLoop(square.slice(0,4)),false);
 const rotated=rotatedLoop(square,.5);assert.ok(Math.abs(cumulative(rotated).at(-1)-total)<1);assert.ok(distance(rotated[0],atDistance(square,cumulative(square),total/2))<1);
 const one=loopPath(square,0,1);assert.ok(Math.abs(cumulative(one).at(-1)-total)<1);assert.ok(distance(one[0],one.at(-1))<1e-6);
 assert.ok(Math.abs(cumulative(loopPath(square,0,2.5)).at(-1)-2.5*total)<1);
 assert.ok(Math.abs(cumulative(loopPath(square,0,.25)).at(-1)-.25*total)<1);
 assert.deepEqual(loopPath(square,0,0),[]);
 assert.ok(Math.abs(nearestOnPath(square,{lat:0,lon:.005})-.005*111319)<50);
});
test('a lap plan drives simulated distance, duration and export path',()=>{
 const total=cumulative(square).at(-1),a=defaults();a.path=square;a.source='routed';
 assert.equal(plannedPath(a),a.path);
 a.loop={start:0,mode:'laps',value:3};
 const plan=loopPlan(a);assert.ok(Math.abs(plan.distance-3*total)<.01);assert.equal(plan.capped,false);assert.equal(plan.laps,3);
 const s=simulate(a);assert.ok(Math.abs(s.distance-3*total)<.01);assert.ok(Math.abs(s.duration-3*total/1000*300)<1);
 a.loop={start:0,mode:'distance',value:total/2};assert.ok(Math.abs(loopPlan(a).distance-total/2)<.01);
 a.loop={start:0,mode:'laps',value:99999};assert.equal(loopPlan(a).capped,true);assert.ok(loopPlan(a).distance<=5000000);
 a.path=path;assert.equal(loopPlan(a),null);assert.deepEqual(plannedPath(a),a.path);
});
test('loop plans round-trip through validation and reject bad values',()=>{
 const a=defaults();a.path=square;a.loop={start:.25,mode:'laps',value:2};
 assert.deepEqual(validateActivity(a).loop,{start:.25,mode:'laps',value:2});
 assert.equal(validateActivity({...a,loop:undefined}).loop,undefined);
 for(const loop of [{start:0,mode:'laps',value:0},{start:1,mode:'laps',value:1},{start:0,mode:'loop',value:1},{start:0,mode:'laps',value:99999},{start:0,mode:'distance',value:6000000}])assert.throws(()=>validateActivity({...a,loop}));
});
test('elevation missing stays missing',()=>{assert.equal(elevationStats([{lon:0,lat:0},{lon:1,lat:0}]).gain,null);});
test('smooth natural simulation normalizes exact duration across midnight',()=>{let a=defaults();a.path=path;a.settings.start='2026-09-27T23:59';a.settings.utcOffset=540;a.settings.mode='natural';a.settings.hrEnabled=true;let s=simulate(a);assert.equal(s.points.at(-1).time-s.points[0].time,Math.round(s.duration*1000));assert.ok(s.points.every((p,i)=>i===0||p.time>s.points[i-1].time));assert.ok(s.points[0].time===Date.UTC(2026,8,27,14,59));assert.deepEqual(s,simulate(a));assert.ok(s.points.at(-1).lon===path.at(-1).lon);assert.ok(s.points.every(p=>p.hr>=30 && p.hr<=240));});
test('constant pace yields stable speeds',()=>{let a=defaults();a.path=path;let s=simulate(a);assert.ok(Math.max(...s.points.map(p=>p.speed))-Math.min(...s.points.map(p=>p.speed))<.00001);});
test('GPX escapes XML and identifies simulation without device spoofing',()=>{let a=defaults();a.path=path;a.name='Run <& " test';a.settings.hrEnabled=true;let x=exportGPX(a,simulate(a));assert.match(x,/Run &lt;&amp; &quot; test/);assert.match(x,/TrackPointExtension\/v1/);assert.match(x,/creator="SimRun"/);assert.match(x,/<gpxtpx:hr>/);assert.ok(!x.includes('Garmin device'));assert.equal(safeFilename('../../hi?!'),'hi');});
test('reject invalid states and empty export',()=>{let a=defaults();assert.throws(()=>simulate(a));a.path=[{lon:200,lat:0},{lon:201,lat:0}];assert.throws(()=>simulate(a));a.path=path;a.settings.sample=0;assert.throws(()=>simulate(a));assert.throws(()=>validateActivity({}));});
test('antimeridian interpolation takes short path',()=>{const p=[{lat:0,lon:179},{lat:0,lon:-179}];let c=cumulative(p);assert.ok(c.at(-1)<223000);assert.ok(Math.abs(atDistance(p,c,c.at(-1)/2).lon)>179.9);});
test('HR-off simulation never leaks imported heart-rate readings',()=>{let a=defaults();a.path=path.map(p=>({...p,hr:155}));a.source='imported';a.settings.hrEnabled=false;assert.ok(simulate(a).points.every(p=>p.hr===undefined));});
test('small fractional last samples stay strictly increasing',()=>{let a=defaults();a.path=[{lat:0,lon:0},{lat:0,lon:0.000001}];assert.throws(()=>simulate(a));a.path=[{lat:0,lon:0},{lat:0,lon:0.00002}];assert.ok(simulate(a).points.length>=2);});
test('HR mean matches target while varying realistically and staying repeatable',()=>{let a=defaults();a.path=path;a.settings.hrEnabled=true;a.settings.mode='natural';const s=simulate(a);let sum=0,min=Infinity,max=-Infinity;for(let i=1;i<s.points.length;i++){sum+=(s.points[i].hr+s.points[i-1].hr)/2*(s.points[i].time-s.points[i-1].time);assert.ok(Math.abs(s.points[i].hr-s.points[i-1].hr)<=8);}for(const p of s.points){min=Math.min(min,p.hr);max=Math.max(max,p.hr);}assert.ok(Math.abs(sum/(s.duration*1000)-a.settings.hrAverage)<.6);assert.ok(max-min>=3);assert.deepEqual(s,simulate(a));});
test('HR starts near resting and ramps up to the target',()=>{let a=defaults();a.path=path;a.settings.hrEnabled=true;a.settings.mode='natural';a.settings.seed=1;const s=simulate(a);const start=s.points[0].hr;assert.ok(start>=75&&start<=100);const at=s.points.find(p=>p.time-s.points[0].time>=60000);assert.ok(at.hr-start>=20);assert.ok(s.points.at(-1).hr>=140&&s.points.at(-1).hr<=160);});
test('zero HR variation removes jitter but keeps the warm-up',()=>{let a=defaults();a.path=path;a.settings.hrEnabled=true;a.settings.mode='natural';a.settings.hrVariation=0;const s=simulate(a);assert.ok(s.points[0].hr<a.settings.hrAverage-40);const tail=s.points.slice(Math.floor(s.points.length/2));assert.ok(tail.every(p=>Math.abs(p.hr-a.settings.hrAverage)<=2));});
test('HR drifts upward through a long steady run',()=>{let a=defaults();a.path=[{lon:0,lat:0,ele:0},{lon:12/111.32,lat:0,ele:0}];a.settings.hrEnabled=true;a.settings.sample=1;a.settings.seed=5;const s=simulate(a);const t0=s.points[0].time,mins=s.points.map(p=>[(p.time-t0)/60000,p.hr]);const band=(lo,hi)=>{const v=mins.filter(([m])=>m>=lo&&m<=hi).map(m=>m[1]);return v.reduce((x,y)=>x+y,0)/v.length;};const last=mins.filter(([m])=>m>=30);const n=last.length;let sx=0,sy=0,sxy=0,sxx=0;for(const[x,y]of last){sx+=x;sy+=y;sxy+=x*y;sxx+=x*x;}assert.ok((n*sxy-sx*sy)/(n*sxx-sx*sx)>0);assert.ok(band(50,60)-band(12,20)>=3);});
test('GPS noise is deterministic, keeps true distance and shifts coordinates',()=>{
 let a=defaults();a.path=path;a.settings.seed=12345;a.settings.gps={noise:8,dropout:0};
 const s=simulate(a);assert.deepEqual(s,simulate(a));
 assert.ok(Math.abs(s.distance-5003.78)<1);
 assert.ok(s.points.every(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)));
 assert.ok(s.points.some(p=>Math.abs(p.lat)>1e-9));
 const clean=simulate({...a,settings:{...a.settings,gps:{noise:0,dropout:0}}});
 assert.deepEqual(s.points.map(p=>p.time),clean.points.map(p=>p.time));
 assert.ok(s.points.some((p,i)=>Math.abs(p.lat-clean.points[i].lat)>1e-9));
});
test('GPS dropout removes fixes into gaps and stays deterministic',()=>{
 let a=defaults();a.path=path;a.settings.seed=12345;a.settings.sample=1;a.settings.gps={noise:0,dropout:.4};
 const s=simulate(a),full=simulate({...a,settings:{...a.settings,gps:{noise:0,dropout:0}}});
 assert.deepEqual(s,simulate(a));
 assert.ok(s.points.length>=2&&s.points.length<full.points.length);
 assert.ok(s.points.every((p,i)=>i===0||p.time>s.points[i-1].time));
 const gap=Math.max(...s.points.map((p,i)=>i?p.time-s.points[i-1].time:0));
 assert.ok(gap>2*s.interval*1000);
});
test('splits honour auto intervals and custom markers',()=>{
 let a=defaults();a.path=path;a.settings.seed=7;a.settings.gps={noise:0,dropout:0};
 const s=simulate(a);a.splits={auto:1000,markers:[2500]};
 const bounds=splitBoundaries(a,s.distance);
 assert.equal(bounds[0],0);assert.equal(bounds.at(-1),s.distance);
 assert.ok(bounds.every((v,i)=>i===0||v>bounds[i-1]));
 assert.ok(bounds.includes(1000)&&bounds.includes(2500));
 const splits=computeSplits(a,s);
 assert.equal(splits.length,bounds.length-1);
 assert.ok(splits.every(sp=>sp.distance>0&&sp.duration>0));
 assert.ok(Math.abs(splits.reduce((n,sp)=>n+sp.duration,0)-s.duration)<.5);
 assert.ok(Math.abs(splits.reduce((n,sp)=>n+sp.distance,0)-s.distance)<1);
});
test('GPS and split settings validate and round-trip',()=>{
 const a=defaults();a.path=path;a.settings.gps={noise:5,dropout:.2};a.splits={auto:1000,markers:[2500,2500,500]};
 const clean=validateActivity(a);
 assert.deepEqual(clean.settings.gps,{noise:5,dropout:.2});
 assert.deepEqual(clean.splits,{auto:1000,markers:[500,2500]});
 assert.equal(validateActivity({...a,splits:undefined}).splits,undefined);
 for(const gps of [{noise:-1,dropout:0},{noise:0,dropout:.9},{noise:100,dropout:0}])assert.throws(()=>validateActivity({...a,settings:{...a.settings,gps}}));
 for(const splits of [{auto:-1,markers:[]},{auto:0,markers:[0]},{auto:0,markers:[6000000]}])assert.throws(()=>validateActivity({...a,splits}));
});
test('GPX export splits a dropout into separate track segments',()=>{
 let a=defaults();a.path=path;a.source='routed';a.settings.seed=12345;a.settings.sample=1;a.settings.gps={noise:0,dropout:.4};
 const xml=exportGPX(a,simulate(a));
 assert.ok((xml.match(/<trkseg>/g)||[]).length>1);
 assert.ok(xml.includes('simulated GPS noise'));
});
