import test from 'node:test';
import assert from 'node:assert/strict';
import {distance, cumulative, atDistance, elevationStats, outAndBack, closeLoop} from '../dist/src/geometry.js';
import {defaults, simulate, durationFor, parseClock, clock, validateActivity} from '../dist/src/model.js';
import {exportGPX, safeFilename} from '../dist/src/gpx.js';
const path=[{lon:0,lat:0,ele:10},{lon:0.045,lat:0,ele:20}];
test('geodesic distance and interpolation',()=>{assert.ok(Math.abs(distance(path[0],path[1])-5003.78)<1);let c=cumulative(path);assert.ok(Math.abs(atDistance(path,c,c.at(-1)/2).lon-.0225)<1e-6);});
test('known pace and speed arithmetic',()=>{assert.equal(durationFor(10000,'run',300,20),3000);assert.equal(durationFor(5000,'run',240,20),1200);assert.equal(durationFor(20000,'ride',300,20),3600);});
test('clock rounds safely',()=>{assert.equal(clock(299.8),'5:00');assert.equal(parseClock('1:02:03'),3723);assert.throws(()=>parseClock('5:99'));});
test('turnaround has no duplicated pivot',()=>{let a=outAndBack([1,2,3]);assert.deepEqual(a,[1,2,3,2,1]);});
test('closing a loop returns to the start and tolerates an empty route',()=>{assert.deepEqual(closeLoop([1,2,3]),[1,2,3,1]);assert.deepEqual(closeLoop([]),[]);});
test('elevation missing stays missing',()=>{assert.equal(elevationStats([{lon:0,lat:0},{lon:1,lat:0}]).gain,null);});
test('smooth natural simulation normalizes exact duration across midnight',()=>{let a=defaults();a.path=path;a.settings.start='2026-09-27T23:59';a.settings.utcOffset=540;a.settings.mode='natural';a.settings.hrEnabled=true;let s=simulate(a);assert.equal(s.points.at(-1).time-s.points[0].time,Math.round(s.duration*1000));assert.ok(s.points.every((p,i)=>i===0||p.time>s.points[i-1].time));assert.ok(s.points[0].time===Date.UTC(2026,8,27,14,59));assert.deepEqual(s,simulate(a));assert.ok(s.points.at(-1).lon===path.at(-1).lon);assert.ok(s.points.every(p=>p.hr>=30 && p.hr<=240));});
test('constant pace yields stable speeds',()=>{let a=defaults();a.path=path;let s=simulate(a);assert.ok(Math.max(...s.points.map(p=>p.speed))-Math.min(...s.points.map(p=>p.speed))<.00001);});
test('GPX escapes XML and identifies simulation without device spoofing',()=>{let a=defaults();a.path=path;a.name='Run <& " test';a.settings.hrEnabled=true;let x=exportGPX(a,simulate(a));assert.match(x,/Run &lt;&amp; &quot; test/);assert.match(x,/TrackPointExtension\/v1/);assert.match(x,/creator="SimRun"/);assert.match(x,/<gpxtpx:hr>/);assert.ok(!x.includes('Garmin device'));assert.equal(safeFilename('../../hi?!'),'hi');});
test('reject invalid states and empty export',()=>{let a=defaults();assert.throws(()=>simulate(a));a.path=[{lon:200,lat:0},{lon:201,lat:0}];assert.throws(()=>simulate(a));a.path=path;a.settings.sample=0;assert.throws(()=>simulate(a));assert.throws(()=>validateActivity({}));});
test('antimeridian interpolation takes short path',()=>{const p=[{lat:0,lon:179},{lat:0,lon:-179}];let c=cumulative(p);assert.ok(c.at(-1)<223000);assert.ok(Math.abs(atDistance(p,c,c.at(-1)/2).lon)>179.9);});
test('HR-off simulation never leaks imported heart-rate readings',()=>{let a=defaults();a.path=path.map(p=>({...p,hr:155}));a.source='imported';a.settings.hrEnabled=false;assert.ok(simulate(a).points.every(p=>p.hr===undefined));});
test('small fractional last samples stay strictly increasing',()=>{let a=defaults();a.path=[{lat:0,lon:0},{lat:0,lon:0.000001}];assert.throws(()=>simulate(a));a.path=[{lat:0,lon:0},{lat:0,lon:0.00002}];assert.ok(simulate(a).points.length>=2);});
test('HR mean approximately matches target and changes smoothly',()=>{let a=defaults();a.path=path;a.settings.hrEnabled=true;a.settings.mode='natural';const s=simulate(a);let sum=0;for(let i=1;i<s.points.length;i++){sum+=(s.points[i].hr+s.points[i-1].hr)/2*(s.points[i].time-s.points[i-1].time);assert.ok(Math.abs(s.points[i].hr-s.points[i-1].hr)<=1);}assert.ok(Math.abs(sum/(s.duration*1000)-a.settings.hrAverage)<.6);});
