import test from 'node:test';
import assert from 'node:assert/strict';
import {distance, cumulative, atDistance, elevationStats, outAndBack, closeLoop, isClosedLoop, loopPath, rotatedLoop, nearestOnPath} from '../dist/src/geometry.js';
import {defaults, simulate, durationFor, parseClock, clock, validateActivity, loopPlan, plannedPath} from '../dist/src/model.js';
import {exportGPX, safeFilename} from '../dist/src/gpx.js';
const path=[{lon:0,lat:0,ele:10},{lon:0.045,lat:0,ele:20}];
test('geodesic distance and interpolation',()=>{assert.ok(Math.abs(distance(path[0],path[1])-5003.78)<1);let c=cumulative(path);assert.ok(Math.abs(atDistance(path,c,c.at(-1)/2).lon-.0225)<1e-6);});
test('known pace and speed arithmetic',()=>{assert.equal(durationFor(10000,'run',300,20),3000);assert.equal(durationFor(5000,'run',240,20),1200);assert.equal(durationFor(20000,'ride',300,20),3600);});
test('clock rounds safely',()=>{assert.equal(clock(299.8),'5:00');assert.equal(parseClock('1:02:03'),3723);assert.throws(()=>parseClock('5:99'));});
test('turnaround has no duplicated pivot',()=>{let a=outAndBack([1,2,3]);assert.deepEqual(a,[1,2,3,2,1]);});
test('closing a loop returns to the start and tolerates an empty route',()=>{assert.deepEqual(closeLoop([1,2,3]),[1,2,3,1]);assert.deepEqual(closeLoop([]),[]);});
const square=[{lat:0,lon:0},{lat:0,lon:.01},{lat:.01,lon:.01},{lat:.01,lon:0},{lat:0,lon:0}];
test('closed loops rotate from a start fraction and walk whole or partial laps',()=>{
 const total=cumulative(square).at(-1);
 assert.equal(isClosedLoop(square),true);assert.equal(isClosedLoop(path),false);assert.equal(isClosedLoop(square.slice(0,4)),false);
 const rotated=rotatedLoop(square,.5);assert.ok(Math.abs(cumulative(rotated).at(-1)-total)<1);assert.ok(distance(rotated[0],atDistance(square,cumulative(square),total/2))<1);
 const one=loopPath(square,0,1);assert.ok(Math.abs(cumulative(one).at(-1)-total)<1);assert.ok(distance(one[0],one.at(-1))<1e-6);
 assert.ok(Math.abs(cumulative(loopPath(square,0,2.5)).at(-1)-2.5*total)<1);
 assert.ok(Math.abs(cumulative(loopPath(square,0,.25)).at(-1)-.25*total)<1);
 assert.deepEqual(loopPath(square,0,0),[]);
 assert.ok(Math.abs(nearestOnPath(square,{lat:0,lon:.005})-.005*111319)<50);
});
test('a lap plan drives simulated distance, duration and export path',()=>{
 const total=cumulative(square).at(-1),a=defaults();a.path=square;a.source='routed';
 assert.equal(plannedPath(a),a.path);
 a.loop={start:0,mode:'laps',value:3};
 const plan=loopPlan(a);assert.ok(Math.abs(plan.distance-3*total)<.01);assert.equal(plan.capped,false);assert.equal(plan.laps,3);
 const s=simulate(a);assert.ok(Math.abs(s.distance-3*total)<.01);assert.ok(Math.abs(s.duration-3*total/1000*300)<1);
 a.loop={start:0,mode:'distance',value:total/2};assert.ok(Math.abs(loopPlan(a).distance-total/2)<.01);
 a.loop={start:0,mode:'laps',value:99999};assert.equal(loopPlan(a).capped,true);assert.ok(loopPlan(a).distance<=5000000);
 a.path=path;assert.equal(loopPlan(a),null);assert.deepEqual(plannedPath(a),a.path);
});
test('loop plans round-trip through validation and reject bad values',()=>{
 const a=defaults();a.path=square;a.loop={start:.25,mode:'laps',value:2};
 assert.deepEqual(validateActivity(a).loop,{start:.25,mode:'laps',value:2});
 assert.equal(validateActivity({...a,loop:undefined}).loop,undefined);
 for(const loop of [{start:0,mode:'laps',value:0},{start:1,mode:'laps',value:1},{start:0,mode:'loop',value:1},{start:0,mode:'laps',value:99999},{start:0,mode:'distance',value:6000000}])assert.throws(()=>validateActivity({...a,loop}));
});
test('elevation missing stays missing',()=>{assert.equal(elevationStats([{lon:0,lat:0},{lon:1,lat:0}]).gain,null);});
test('smooth natural simulation normalizes exact duration across midnight',()=>{let a=defaults();a.path=path;a.settings.start='2026-09-27T23:59';a.settings.utcOffset=540;a.settings.mode='natural';a.settings.hrEnabled=true;let s=simulate(a);assert.equal(s.points.at(-1).time-s.points[0].time,Math.round(s.duration*1000));assert.ok(s.points.every((p,i)=>i===0||p.time>s.points[i-1].time));assert.ok(s.points[0].time===Date.UTC(2026,8,27,14,59));assert.deepEqual(s,simulate(a));assert.ok(s.points.at(-1).lon===path.at(-1).lon);assert.ok(s.points.every(p=>p.hr>=30 && p.hr<=240));});
test('constant pace yields stable speeds',()=>{let a=defaults();a.path=path;let s=simulate(a);assert.ok(Math.max(...s.points.map(p=>p.speed))-Math.min(...s.points.map(p=>p.speed))<.00001);});
test('GPX escapes XML and identifies simulation without device spoofing',()=>{let a=defaults();a.path=path;a.name='Run <& " test';a.settings.hrEnabled=true;let x=exportGPX(a,simulate(a));assert.match(x,/Run &lt;&amp; &quot; test/);assert.match(x,/TrackPointExtension\/v1/);assert.match(x,/creator="SimRun"/);assert.match(x,/<gpxtpx:hr>/);assert.ok(!x.includes('Garmin device'));assert.equal(safeFilename('../../hi?!'),'hi');});
test('reject invalid states and empty export',()=>{let a=defaults();assert.throws(()=>simulate(a));a.path=[{lon:200,lat:0},{lon:201,lat:0}];assert.throws(()=>simulate(a));a.path=path;a.settings.sample=0;assert.throws(()=>simulate(a));assert.throws(()=>validateActivity({}));});
test('antimeridian interpolation takes short path',()=>{const p=[{lat:0,lon:179},{lat:0,lon:-179}];let c=cumulative(p);assert.ok(c.at(-1)<223000);assert.ok(Math.abs(atDistance(p,c,c.at(-1)/2).lon)>179.9);});
test('HR-off simulation never leaks imported heart-rate readings',()=>{let a=defaults();a.path=path.map(p=>({...p,hr:155}));a.source='imported';a.settings.hrEnabled=false;assert.ok(simulate(a).points.every(p=>p.hr===undefined));});
test('small fractional last samples stay strictly increasing',()=>{let a=defaults();a.path=[{lat:0,lon:0},{lat:0,lon:0.000001}];assert.throws(()=>simulate(a));a.path=[{lat:0,lon:0},{lat:0,lon:0.00002}];assert.ok(simulate(a).points.length>=2);});
test('HR mean approximately matches target and changes smoothly',()=>{let a=defaults();a.path=path;a.settings.hrEnabled=true;a.settings.mode='natural';const s=simulate(a);let sum=0;for(let i=1;i<s.points.length;i++){sum+=(s.points[i].hr+s.points[i-1].hr)/2*(s.points[i].time-s.points[i-1].time);assert.ok(Math.abs(s.points[i].hr-s.points[i-1].hr)<=1);}assert.ok(Math.abs(sum/(s.duration*1000)-a.settings.hrAverage)<.6);});
