import test from 'node:test';
import assert from 'node:assert/strict';
import {cues,cueSheetCSV,downloadCues} from '../dist/src/cues.js';
import {defaults,simulate} from '../dist/src/model.js';
const east=[{lat:0,lon:0},{lat:0,lon:0.01}];
const corner=[{lat:0,lon:0},{lat:0,lon:0.01},{lat:0.01,lon:0.01}];
test('a right-angled route reports one turn with start and finish cues',()=>{
 const list=cues(corner);
 assert.equal(list.length,3);
 assert.equal(list[0].turn,'Start');
 assert.equal(list[0].heading,90);
 assert.equal(list[1].turn,'Turn left');
 assert.equal(list[1].heading,0);
 assert.equal(list[2].turn,'Finish');
 assert.ok(list[1].distance>0&&list[1].distance<list[2].distance);
 assert.ok(list.every((cue,i)=>i===0||cue.distance>list[i-1].distance));
});
test('a straight route and a two-point route carry no manoeuvres',()=>{
 const straight=cues([{lat:0,lon:0},{lat:0,lon:0.01},{lat:0,lon:0.02}]);
 assert.deepEqual(straight.map(c=>c.turn),['Start','Finish']);
 assert.deepEqual(cues(east).map(c=>c.turn),['Start','Finish']);
 assert.deepEqual(cues([]),[]);
});
test('reversing direction is reported as a U-turn',()=>{
 const list=cues([{lat:0,lon:0},{lat:0,lon:0.01},{lat:0,lon:0.02},{lat:0,lon:0.01}]);
 assert.equal(list.filter(c=>c.turn==='U-turn').length,1);
});
test('opposite corners distinguish left from right',()=>{
 const right=cues([{lat:0,lon:0},{lat:0.01,lon:0},{lat:0.01,lon:0.01}]);
 assert.equal(right[1].turn,'Turn right');
});
const activity=()=>{const a=defaults();a.name='Loop, "quoted"';a.path=corner;a.source='routed';return a;};
test('the cue sheet is a CSV table with a simulated-activity label',()=>{
 const a=activity(),csv=cueSheetCSV(a,simulate(a),'metric');
 const lines=csv.split('\r\n');
 assert.equal(lines[0],'SimRun cue sheet');
 assert.ok(lines.includes('Note,Simulated activity generated by SimRun; not a recorded workout.'));
 assert.equal(lines[7],'');
 assert.equal(lines[8],'#,Distance (km),Elapsed,Turn,Heading (deg),Latitude,Longitude');
 assert.equal(lines[9].split(',')[3],'Start');
 assert.equal(lines.at(-1),'');
 assert.ok(lines.length>=11);
});
test('the cue sheet respects units and escapes activity names',()=>{
 const a=activity(),metric=cueSheetCSV(a,simulate(a),'metric'),imperial=cueSheetCSV(a,simulate(a),'imperial');
 assert.match(metric,/Distance \(km\)/);
 assert.match(imperial,/Distance \(mi\)/);
 assert.match(metric,/Activity,"Loop, ""quoted"""/);
});
test('cue sheets cannot be exported from an unresolved draft',()=>{
 const a=activity();a.source='draft';
 assert.throws(()=>downloadCues(a,simulate(a),'metric'),/Resolve the route/);
});
