import test from 'node:test';
import assert from 'node:assert/strict';
import {defaults,simulate} from '../dist/src/model.js';
import {exportGPX} from '../dist/src/gpx.js';
import {exportTCX} from '../dist/src/tcx.js';
import {exportFIT} from '../dist/src/fit.js';

function activity() {
 const a=defaults();a.path=[{lat:0,lon:0,ele:0},{lat:0,lon:.005,ele:4}];a.waypoints=a.path;a.source='routed';
 a.name='Tempo <&> "test"';a.description='Intervals & recovery <easy> "steady"';
 a.settings={...a.settings,start:'2024-01-02T03:04',utcOffset:0,seed:44,sample:5};
 return a;
}

test('GPX metadata XML-escapes and carries the activity name and description',()=>{
 const a=activity(),xml=exportGPX(a,simulate(a));
 assert.ok(xml.includes('<metadata><name>Tempo &lt;&amp;&gt; &quot;test&quot;</name>'));
 assert.ok(xml.includes('Activity description: Intervals &amp; recovery &lt;easy&gt; &quot;steady&quot;'));
 assert.ok(xml.includes('not a recorded workout or device measurement'));
});

test('TCX notes carry escaped activity name and description with the simulated label',()=>{
 const a=activity(),xml=exportTCX(a,simulate(a));
 assert.ok(xml.includes('Activity name: Tempo &lt;&amp;&gt; &quot;test&quot;'));
 assert.ok(xml.includes('Description: Intervals &amp; recovery &lt;easy&gt; &quot;steady&quot;'));
 assert.ok(xml.includes('is a simulated activity generated by SimRun'));
 assert.ok(xml.includes('not a recorded workout or device measurement'));
});

test('FIT carries activity name as free text and preserves development-only identifiers',()=>{
 const a=activity(),bytes=exportFIT(a,simulate(a)),text=new TextDecoder().decode(bytes);
 assert.ok(text.includes(a.name));
 assert.ok(text.includes('Tempo'));
 assert.equal(bytes.includes(255),true);
});
