import {t} from './i18n.js';
import type {Activity,Point,Simulation,RouteData} from './types.js';
import {atDistance,cumulative} from './geometry.js';
import {clock,plannedPath} from './model.js';
import {download,safeFilename} from './gpx.js';
import {sportLabel} from './sports.js';
export interface Cue {distance:number;turn:string;heading:number;lat:number;lon:number;streetName?:string}
const rad=Math.PI/180;
/** Initial great-circle bearing in degrees clockwise from north. */
const bearing=(a:Point,b:Point):number=>{
 const y=Math.sin((b.lon-a.lon)*rad)*Math.cos(b.lat*rad);
 const x=Math.cos(a.lat*rad)*Math.sin(b.lat*rad)-Math.sin(a.lat*rad)*Math.cos(b.lat*rad)*Math.cos((b.lon-a.lon)*rad);
 return (Math.atan2(y,x)/rad+360)%360;
};
const normalise=(degrees:number):number=>((degrees+540)%360)-180;
const classify=(delta:number):string=>{
 const size=Math.abs(delta);
 if(size>=160)return 'U-turn';
 if(size>=120)return delta>0?'Sharp right':'Sharp left';
 if(size>=45)return delta>0?'Turn right':'Turn left';
 return delta>0?'Slight right':'Slight left';
};
/**
 * Turns are read from the route geometry itself, so they work for routed, imported
 * and loop-planned paths alike. Heading changes are measured across a short span
 * either side of each vertex to keep dense geometry from inventing manoeuvres.
 */
export function cues(path:Point[],span=25,threshold=25,routeData?:RouteData):Cue[] {
 if(path.length<2)return [];
 const c=cumulative(path),total=c[c.length-1];
 if(!(total>0))return [];
 const streetName=(d:number):string|undefined=>{let name:string|undefined;for(const span of routeData?.streetNames??[])if(d>=span.start&&d<=span.end)name=span.name;return name;};
 const step=Math.min(span,Math.max(5,total/8));
 const heading=(i:number):number=>Math.round(bearing(path[i],path[Math.min(path.length-1,i+1)]))%360;
 const found:{distance:number;turn:string;heading:number;lat:number;lon:number;angle:number;streetName?:string}[]=[];
 for(let i=1;i<path.length-1;i++){
  const d=c[i];
  if(d<step||total-d<step)continue;
  const before=atDistance(path,c,d-step),after=atDistance(path,c,d+step);
  const delta=normalise(bearing(path[i],after)-bearing(before,path[i]));
  if(Math.abs(delta)<threshold)continue;
  found.push({distance:d,turn:classify(delta),heading:Math.round(bearing(path[i],after))%360,lat:path[i].lat,lon:path[i].lon,angle:Math.abs(delta),...(streetName(d)?{streetName:streetName(d)}:{})});
 }
 // Two vertices inside one corner describe the same manoeuvre; keep the sharper one.
 const merged:typeof found=[];
 for(const cue of found){
  const last=merged[merged.length-1];
  if(last&&cue.distance-last.distance<step){if(cue.angle>last.angle)merged[merged.length-1]=cue;continue;}
  merged.push(cue);
 }
 return [
  {distance:0,turn:'Start',heading:heading(0),lat:path[0].lat,lon:path[0].lon,...(streetName(0)?{streetName:streetName(0)}:{})},
  ...merged.map(({distance,turn,heading,lat,lon,streetName})=>({distance,turn,heading,lat,lon,...(streetName?{streetName}:{})})),
  {distance:total,turn:'Finish',heading:heading(path.length-2),lat:path[path.length-1].lat,lon:path[path.length-1].lon,...(streetName(total)?{streetName:streetName(total)}:{})},
 ];
}
/** Simulated elapsed seconds at a cumulative route distance, read from the simulation. */
const elapsed=(sim:Simulation,distance:number):number=>{
 const points=sim.points;
 if(points.length<2)return 0;
 let i=1;while(i<points.length-1&&points[i].distance<distance)i++;
 const a=points[i-1],b=points[i],segment=b.distance-a.distance,t=segment>0?(distance-a.distance)/segment:0;
 return (a.time+t*(b.time-a.time)-points[0].time)/1000;
};
const cell=(value:string|number):string=>{const s=String(value);return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;};
const row=(...values:(string|number)[]):string=>values.map(cell).join(',');
export function cueSheetCSV(a:Activity,sim:Simulation,units:'metric'|'imperial'):string {
 const list=cues(plannedPath(a),25,25,a.routeData),imperial=units==='imperial',factor=imperial?1609.344:1000,label=imperial?'mi':'km';
 return [
  'SimRun cue sheet',
  row('Activity',a.name),
  row('Sport',sportLabel(a.settings.sport)),
  row('Distance',`${(sim.distance/factor).toFixed(2)} ${label}`),
  row('Simulated elapsed',clock(sim.duration)),
  row('Turns','Derived from route geometry. Street names are included only when provided by the routing service; landmarks are not included.'),
  row('Note','Simulated activity generated by SimRun; not a recorded workout.'),
  '',
  row('#',`Distance (${label})`,'Elapsed','Turn','Heading (deg)','Latitude','Longitude','Street name'),
  ...list.map((cue,i)=>row(i+1,(cue.distance/factor).toFixed(3),clock(elapsed(sim,cue.distance)),cue.turn,cue.heading,cue.lat.toFixed(6),cue.lon.toFixed(6),cue.streetName??'')),
 ].join('\r\n')+'\r\n';
}
export function downloadCues(a:Activity,sim:Simulation,units:'metric'|'imperial'):void {
 if(a.source==='draft')throw Error(t('Resolve the route before exporting. A waypoint preview is not a routed path.'));
 download(cueSheetCSV(a,sim,units),`${a.settings.start.slice(0,10)}-${safeFilename(a.name)}-cue-sheet.csv`,'text/csv;charset=utf-8');
}
