import type {Activity,Point,Simulation} from './types.js';
import {PRODUCT,importedActivity,simulate,startTime} from './model.js';
import {validPoint} from './geometry.js';
export const escapeXML=(s:string)=>s.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));
export function safeFilename(name:string):string{return name.normalize('NFKD').replace(/[^a-zA-Z0-9 _-]/g,'').trim().replace(/\s+/g,'-').slice(0,70)||'simulated-activity';}
export function exportGPX(a:Activity,s:Simulation):string {
 if(s.points.length<2)throw Error('Route needs at least two points.');
 let previous=-Infinity;
 for(const p of s.points){if(!validPoint(p)||!Number.isFinite(p.time)||p.time<=previous||!Number.isFinite(new Date(p.time).getTime()))throw Error('Export needs valid coordinates and strictly increasing timestamps.');if(p.ele!==undefined&&!Number.isFinite(p.ele))throw Error('Invalid elevation.');if(p.hr!==undefined&&(!Number.isInteger(p.hr)||p.hr<0||p.hr>255))throw Error('Invalid heart-rate data.');previous=p.time;}
 const name=escapeXML(a.name||'Simulated activity');
 const pts=s.points.map(p=>`<trkpt lat="${p.lat.toFixed(7)}" lon="${p.lon.toFixed(7)}">${p.ele===undefined?'':`<ele>${p.ele.toFixed(2)}</ele>`}<time>${new Date(p.time).toISOString()}</time>${p.hr===undefined?'':`<extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>${p.hr}</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions>`}</trkpt>`).join('\n');
 return `<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="${PRODUCT}" xmlns="http://www.topografix.com/GPX/1/1" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd"><metadata><name>${name}</name><desc>Simulated activity generated by ${PRODUCT}; not a recorded workout or device measurement.</desc><time>${new Date(s.points[0].time).toISOString()}</time></metadata><trk><name>${name}</name><type>${a.settings.sport==='run'?'running':'cycling'}</type><trkseg>\n${pts}\n</trkseg></trk></gpx>`;
}
export function download(text:string,filename:string,type:string):void {const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export function downloadActivity(a:Activity):void {if(a.source==='draft')throw Error('Resolve the route before exporting. A waypoint preview is not a routed path.');download(exportGPX(a,simulate(a)),`${a.settings.start.slice(0,10)}-${safeFilename(a.name)}.gpx`,'application/gpx+xml');}
export function importGPX(xml:string):{activity:Activity;notice:string} {
 if(xml.length>15000000)throw Error('GPX must be smaller than 15 MB.');if(/<!DOCTYPE|<!ENTITY/i.test(xml))throw Error('GPX with document types or entities is not supported.');
 const doc=new DOMParser().parseFromString(xml,'application/xml');
 if(doc.getElementsByTagName('parsererror').length||doc.documentElement.localName!=='gpx')throw Error('This file is not valid GPX XML.');
 const elements=(node:Element|Document,name:string)=>Array.from(node.getElementsByTagNameNS('*',name));
 const direct=(node:Element,name:string)=>Array.from(node.children).find(e=>e.localName===name)?.textContent?.trim();
 const tracks=elements(doc,'trkseg'),routes=elements(doc,'rte');
 // Keep disjoint segments separate: never invent a connecting line across gaps.
 const candidates=(tracks.length?tracks:routes).map(seg=>elements(seg,tracks.length?'trkpt':'rtept')).filter(a=>a.length>=2);
 if(!candidates.length)throw Error('GPX has no track or route with at least two points.');
 if(candidates.reduce((n,a)=>n+a.length,0)>100000)throw Error('GPX exceeds 100,000 points.');
 const nodes=candidates.sort((a,b)=>b.length-a.length)[0];
 const points:Point[]=nodes.map(node=>{
  const la=node.getAttribute('lat'),lo=node.getAttribute('lon');const p:Point={lat:Number(la),lon:Number(lo)};
  if(la===null||lo===null||la.trim()===''||lo.trim()===''||!validPoint(p))throw Error('GPX contains invalid coordinates.');
  const ele=direct(node,'ele'),time=direct(node,'time'),hr=elements(node,'hr')[0]?.textContent?.trim();
  if(ele!==undefined&&ele!==''&&Number.isFinite(Number(ele))&&Math.abs(Number(ele))<=12000)p.ele=Number(ele);
  if(time&&/Z$|[+-]\d{2}:\d{2}$/.test(time)&&Number.isFinite(Date.parse(time)))p.time=Date.parse(time);
  if(hr&&Number.isFinite(Number(hr))&&Number(hr)>=0&&Number(hr)<=255)p.hr=Number(hr);return p;
 });
 const {activity:a,notices}=importedActivity(points,elements(doc,'name')[0]?.textContent??'',elements(doc,'type')[0]?.textContent??'','GPX');
 if(candidates.length>1)notices.unshift(`Imported the largest of ${candidates.length} disjoint segments; no artificial connections were added.`);
 return {activity:a,notice:notices.join(' ')};
}
