import type {Activity,Point,Sample,Simulation} from './types.js';
import {PRODUCT,importedActivity} from './model.js';
import {validPoint} from './geometry.js';
import {escapeXML} from './gpx.js';
import {cues} from './cues.js';

const TCX_NS='http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2';
const TPX_NS='http://www.garmin.com/xmlschemas/ActivityExtension/v2';

function validated(s:Simulation):Sample[] {
 if(s.points.length<2)throw Error('Route needs at least two points.');
 let previous=-Infinity;
 for(const p of s.points){if(!validPoint(p)||!Number.isFinite(p.time)||p.time<=previous||!Number.isFinite(new Date(p.time).getTime()))throw Error('Export needs valid coordinates and strictly increasing timestamps.');if(p.ele!==undefined&&!Number.isFinite(p.ele))throw Error('Invalid elevation.');if(p.hr!==undefined&&(!Number.isInteger(p.hr)||p.hr<0||p.hr>255))throw Error('Invalid heart-rate data.');previous=p.time;}
 return s.points;
}
const sportText=(a:Activity):string=>a.settings.sport==='ride'?'Biking':'Running';
const iso=(time:number):string=>new Date(time).toISOString();

function trackpoint(p:Sample):string {
 const alt=p.ele===undefined?'':`<AltitudeMeters>${p.ele.toFixed(2)}</AltitudeMeters>`;
 const hr=p.hr===undefined?'':`<HeartRateBpm><Value>${p.hr}</Value></HeartRateBpm>`;
 const tpx=[p.power===undefined?'':`<Watts>${p.power}</Watts>`,p.cad===undefined?'':`<RunCadence>${p.cad}</RunCadence>`].join('');
 return `<Trackpoint><Time>${iso(p.time)}</Time><Position><LatitudeDegrees>${p.lat.toFixed(6)}</LatitudeDegrees><LongitudeDegrees>${p.lon.toFixed(6)}</LongitudeDegrees></Position>${alt}${hr}${tpx?`<Extensions><TPX xmlns="${TPX_NS}">${tpx}</TPX></Extensions>`:''}</Trackpoint>`;
}

function timeAt(points:Sample[],distance:number):number {
 const last=points[points.length-1];
 if(distance<=points[0].distance)return points[0].time;
 if(distance>=last.distance)return last.time;
 // Interpolate within the segment that contains the distance, not the one after it.
 let i=1;while(i<points.length-1&&points[i].distance<distance)i++;
 const a=points[i-1],b=points[i],span=b.distance-a.distance,t=span>0?(distance-a.distance)/span:0;
 return a.time+t*(b.time-a.time);
}

export function exportTCX(a:Activity,s:Simulation):string {
 const points=validated(s);
 const name=escapeXML(a.name||'Simulated activity');
 const hrs=points.map(p=>p.hr).filter((h):h is number=>h!==undefined);
 const averageHr=a.settings.hrEnabled&&hrs.length?`<AverageHeartRateBpm><Value>${Math.round(hrs.reduce((x,y)=>x+y,0)/hrs.length)}</Value></AverageHeartRateBpm>`:'';
 const maximumSpeed=Math.max(...points.map(p=>p.speed));
 const track=points.map(trackpoint).join('');
 return `<?xml version="1.0" encoding="UTF-8"?>\n<TrainingCenterDatabase xmlns="${TCX_NS}" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="${TCX_NS} ${TCX_NS}/tcx.xsd"><Activities><Activity Sport="${sportText(a)}"><Id>${iso(points[0].time)}</Id><Lap StartTime="${iso(points[0].time)}"><TotalTimeSeconds>${s.duration.toFixed(2)}</TotalTimeSeconds><DistanceMeters>${s.distance.toFixed(2)}</DistanceMeters><MaximumSpeed>${maximumSpeed.toFixed(3)}</MaximumSpeed>${averageHr}<Intensity>Active</Intensity><Track>${track}</Track></Lap><Notes>${name} is a simulated activity generated by ${PRODUCT}; it is not a recorded workout or device measurement.</Notes></Activity></Activities></TrainingCenterDatabase>`;
}

const courseType=(turn:string):string=>turn.includes('left')?'Left':turn.includes('right')?'Right':'Generic';

export function exportTCXCourse(a:Activity,s:Simulation):string {
 const points=validated(s);
 const track=points.map(trackpoint).join('');
 const coursePoints=cues(points).map(c=>`<CoursePoint><Name>${escapeXML(c.turn)}</Name><Time>${iso(timeAt(points,c.distance))}</Time><Position><LatitudeDegrees>${c.lat.toFixed(6)}</LatitudeDegrees><LongitudeDegrees>${c.lon.toFixed(6)}</LongitudeDegrees></Position><Type>${courseType(c.turn)}</Type><Notes>Simulated course point derived from route geometry; no street names are known.</Notes></CoursePoint>`).join('');
 return `<?xml version="1.0" encoding="UTF-8"?>\n<Courses xmlns="${TCX_NS}" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="${TCX_NS} ${TCX_NS}/tcx.xsd"><Course><Track>${track}</Track>${coursePoints}</Course></Courses>`;
}

export function importTCX(xml:string):{activity:Activity;notice:string} {
 if(xml.length>15000000)throw Error('TCX must be smaller than 15 MB.');if(/<!DOCTYPE|<!ENTITY/i.test(xml))throw Error('TCX with document types or entities is not supported.');
 const doc=new DOMParser().parseFromString(xml,'application/xml');
 if(doc.getElementsByTagName('parsererror').length||doc.documentElement.localName!=='TrainingCenterDatabase')throw Error('This file is not valid TCX XML.');
 const elements=(node:Element|Document,name:string)=>Array.from(node.getElementsByTagNameNS('*',name));
 const direct=(node:Element,name:string)=>Array.from(node.children).find(e=>e.localName===name)?.textContent?.trim();
 const tracks=elements(doc,'Track').map(t=>elements(t,'Trackpoint')).filter(a=>a.length>=2);
 if(!tracks.length)throw Error('TCX has no track with at least two points.');
 if(tracks.reduce((n,a)=>n+a.length,0)>100000)throw Error('TCX exceeds 100,000 points.');
 const nodes=tracks.sort((a,b)=>b.length-a.length)[0];
 const points:Point[]=nodes.map(node=>{
  const lat=direct(node,'LatitudeDegrees'),lon=direct(node,'LongitudeDegrees');
  const p:Point={lat:Number(lat),lon:Number(lon)};
  if(lat===undefined||lon===undefined||lat===''||lon===''||!validPoint(p))throw Error('TCX contains invalid coordinates.');
  const ele=direct(node,'AltitudeMeters'),time=direct(node,'Time'),hr=elements(node,'Value')[0]?.textContent?.trim();
  if(ele!==undefined&&ele!==''&&Number.isFinite(Number(ele))&&Math.abs(Number(ele))<=12000)p.ele=Number(ele);
  if(time&&/Z$|[+-]\d{2}:\d{2}$/.test(time)&&Number.isFinite(Date.parse(time)))p.time=Date.parse(time);
  if(hr&&Number.isFinite(Number(hr))&&Number(hr)>=0&&Number(hr)<=255)p.hr=Number(hr);return p;
 });
 const activity=elements(doc,'Activity')[0];
 const name=activity?direct(activity,'Id')??elements(activity,'Notes')[0]?.textContent??'':'';
 const sport=activity?.getAttribute('Sport')??'';
 const {activity:a,notices}=importedActivity(points,name,sport,'TCX');
 return {activity:a,notice:notices.join(' ')};
}
